name: Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/call-ci.yml
    with:
      environment: Production
